# Generated by Django 4.2.1 on 2023-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
        migrations.RenameModel(
            old_name='Record',
            new_name='Records',
        ),
    ]
