# Generated by Django 4.2.1 on 2023-05-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devlog', '0002_rename_project_projects_rename_record_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='records',
            name='changelog',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='records',
            name='documentation',
            field=models.TextField(default=''),
        ),
    ]
